<a href="https://colab.research.google.com/github/f-ssemwanga/data_science-sessions/blob/main/Data_Science_Session_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import tensorflow as tf
import numpy as np

print("TensorFlow version", tf.__version__)



TensorFlow version 2.12.0


In [ ]:
scaler = tf.constant(7)
scaler.ndim #single dimention

0

In [ ]:
vector = tf.constant([5,5])
vector.ndim

1

In [ ]:
matrix = tf.constant([[1,2], [3,4]])
matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1,2,3], [4,5,6]]])
tensor
tensor.ndim

3

In [ ]:
#tensor operations
#addition - used adding mean value when you have missing value - you use mean to compute and replace the missing values
addedTensor = tensor +10
addedTensor


<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[11, 12, 13],
        [14, 15, 16]]], dtype=int32)>

In [ ]:
#tensor subtration

subtractedTensor = tensor -7
subtractedTensor

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[-6, -5, -4],
        [-3, -2, -1]]], dtype=int32)>

In [17]:
#average mean
x = np.ones((2,2)) 
y = np.zeros((2,2))
avg = tf.keras.layers.Average()([x,y])
avg.numpy().tolist()

[[0.5, 0.5], [0.5, 0.5]]